-- MySQL Script generated by MySQL Workbench
-- Sun Sep 21 23:17:29 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dac_dbt_2025
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dac_dbt_2025
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dac_dbt_2025` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `dac_dbt_2025` ;

-- -----------------------------------------------------
-- Table `dac_dbt_2025`.`dept`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dac_dbt_2025`.`dept` (
  `deptcode` VARCHAR(15) NOT NULL,
  `deptname` VARCHAR(60) NULL DEFAULT NULL,
  `budget` INT NULL DEFAULT NULL,
  PRIMARY KEY (`deptcode`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dac_dbt_2025`.`desig`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dac_dbt_2025`.`desig` (
  `desigcode` VARCHAR(15) NOT NULL,
  `designame` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`desigcode`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dac_dbt_2025`.`grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dac_dbt_2025`.`grade` (
  `gradecode` VARCHAR(15) NOT NULL,
  `gradelevel` VARCHAR(30) NOT NULL,
  `gradedescription` VARCHAR(60) NULL DEFAULT NULL,
  `basic` INT NULL DEFAULT NULL,
  PRIMARY KEY (`gradecode`, `gradelevel`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dac_dbt_2025`.`emp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dac_dbt_2025`.`emp` (
  `empcode` VARCHAR(15) NOT NULL,
  `empname` VARCHAR(60) NULL DEFAULT NULL,
  `deptcode` VARCHAR(15) NULL DEFAULT NULL,
  `birthdate` DATE NOT NULL,
  `joindate` DATE NOT NULL,
  `sex` CHAR(1) NULL DEFAULT NULL,
  `desigcode` VARCHAR(15) NULL DEFAULT NULL,
  `supcode` VARCHAR(15) NULL DEFAULT NULL,
  `gradecode` VARCHAR(15) NULL DEFAULT NULL,
  `gradelevel` VARCHAR(30) NULL DEFAULT NULL,
  `basicpay` INT NULL DEFAULT NULL,
  PRIMARY KEY (`empcode`),
  INDEX `deptcode` (`deptcode` ASC) VISIBLE,
  INDEX `desigcode` (`desigcode` ASC) VISIBLE,
  INDEX `supcode` (`supcode` ASC) VISIBLE,
  INDEX `gradecode` (`gradecode` ASC, `gradelevel` ASC) VISIBLE,
  CONSTRAINT `emp_ibfk_1`
    FOREIGN KEY (`deptcode`)
    REFERENCES `dac_dbt_2025`.`dept` (`deptcode`),
  CONSTRAINT `emp_ibfk_2`
    FOREIGN KEY (`desigcode`)
    REFERENCES `dac_dbt_2025`.`desig` (`desigcode`),
  CONSTRAINT `emp_ibfk_3`
    FOREIGN KEY (`supcode`)
    REFERENCES `dac_dbt_2025`.`emp` (`empcode`),
  CONSTRAINT `emp_ibfk_4`
    FOREIGN KEY (`gradecode` , `gradelevel`)
    REFERENCES `dac_dbt_2025`.`grade` (`gradecode` , `gradelevel`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dac_dbt_2025`.`history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dac_dbt_2025`.`history` (
  `empcode` VARCHAR(15) NOT NULL,
  `changedate` DATE NOT NULL,
  `desigcode` VARCHAR(15) NOT NULL,
  `gradecode` VARCHAR(15) NOT NULL,
  `gradelevel` VARCHAR(30) NOT NULL,
  `basicpay` INT NULL DEFAULT NULL,
  PRIMARY KEY (`empcode`, `changedate`, `desigcode`, `gradecode`, `gradelevel`),
  INDEX `desigcode` (`desigcode` ASC) VISIBLE,
  INDEX `gradecode` (`gradecode` ASC, `gradelevel` ASC) VISIBLE,
  CONSTRAINT `history_ibfk_1`
    FOREIGN KEY (`empcode`)
    REFERENCES `dac_dbt_2025`.`emp` (`empcode`),
  CONSTRAINT `history_ibfk_2`
    FOREIGN KEY (`desigcode`)
    REFERENCES `dac_dbt_2025`.`desig` (`desigcode`),
  CONSTRAINT `history_ibfk_3`
    FOREIGN KEY (`gradecode` , `gradelevel`)
    REFERENCES `dac_dbt_2025`.`grade` (`gradecode` , `gradelevel`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dac_dbt_2025`.`salary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dac_dbt_2025`.`salary` (
  `empcode` VARCHAR(15) NOT NULL,
  `salmonth` DATE NOT NULL,
  `basic` INT NULL DEFAULT NULL,
  `allow` INT NULL DEFAULT NULL,
  `deduct` INT NULL DEFAULT NULL,
  PRIMARY KEY (`empcode`, `salmonth`),
  CONSTRAINT `salary_ibfk_1`
    FOREIGN KEY (`empcode`)
    REFERENCES `dac_dbt_2025`.`emp` (`empcode`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `dac_dbt_2025` ;

-- -----------------------------------------------------
-- Placeholder table for view `dac_dbt_2025`.`deptmax`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dac_dbt_2025`.`deptmax` (`deptcode` INT, `deptname` INT, `employeeSalary` INT);

-- -----------------------------------------------------
-- Placeholder table for view `dac_dbt_2025`.`empactualsalary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dac_dbt_2025`.`empactualsalary` (`empcode` INT, `empname` INT, `max(s.basic+s.allow-s.deduct)` INT, `deptcode` INT);

-- -----------------------------------------------------
-- Placeholder table for view `dac_dbt_2025`.`empmax`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dac_dbt_2025`.`empmax` (`empcode` INT, `empname` INT, `deptcode` INT, `totalpay` INT);

-- -----------------------------------------------------
-- Placeholder table for view `dac_dbt_2025`.`femaleemployee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dac_dbt_2025`.`femaleemployee` (`empcode` INT, `empname` INT, `sex` INT, `deptname` INT, `totalSalary` INT);

-- -----------------------------------------------------
-- Placeholder table for view `dac_dbt_2025`.`maleemployee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dac_dbt_2025`.`maleemployee` (`empcode` INT, `empname` INT, `sex` INT, `deptname` INT, `totalSalary` INT);

-- -----------------------------------------------------
-- Placeholder table for view `dac_dbt_2025`.`maxfemaleemployee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dac_dbt_2025`.`maxfemaleemployee` (`empcode` INT, `empname` INT, `sex` INT, `deptname` INT, `max(s.basic + s.allow - s.deduct)` INT);

-- -----------------------------------------------------
-- Placeholder table for view `dac_dbt_2025`.`maxone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dac_dbt_2025`.`maxone` (`empcode` INT, `empname` INT, `TotalPay` INT);

-- -----------------------------------------------------
-- Placeholder table for view `dac_dbt_2025`.`maxsalaries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dac_dbt_2025`.`maxsalaries` (`empcode` INT, `empname` INT, `deptcode` INT, `totalPay` INT);

-- -----------------------------------------------------
-- Placeholder table for view `dac_dbt_2025`.`minfemalesalary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dac_dbt_2025`.`minfemalesalary` (`empcode` INT, `empname` INT, `sex` INT, `totalSalary` INT);

-- -----------------------------------------------------
-- View `dac_dbt_2025`.`deptmax`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dac_dbt_2025`.`deptmax`;
USE `dac_dbt_2025`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `dac_dbt_2025`.`deptmax` (`deptcode`,`deptname`,`employeeSalary`) AS select `d`.`deptcode` AS `deptcode`,`d`.`deptname` AS `deptname`,max(`dac_dbt_2025`.`a`.`totalSalary`) AS `employeeSalary` from (`dac_dbt_2025`.`dept` `d` join `dac_dbt_2025`.`empactualsalary` `a` on((`d`.`deptcode` = `dac_dbt_2025`.`a`.`deptcode`))) group by `d`.`deptcode`;

-- -----------------------------------------------------
-- View `dac_dbt_2025`.`empactualsalary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dac_dbt_2025`.`empactualsalary`;
USE `dac_dbt_2025`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `dac_dbt_2025`.`empactualsalary` (`empcode`,`empname`,`totalSalary`,`deptcode`) AS select `e`.`empcode` AS `empcode`,`e`.`empname` AS `empname`,max(((`s`.`basic` + `s`.`allow`) - `s`.`deduct`)) AS `max(s.basic+s.allow-s.deduct)`,`e`.`deptcode` AS `deptcode` from (`dac_dbt_2025`.`emp` `e` join `dac_dbt_2025`.`salary` `s` on((`e`.`empcode` = `s`.`empcode`))) group by `s`.`empcode`;

-- -----------------------------------------------------
-- View `dac_dbt_2025`.`empmax`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dac_dbt_2025`.`empmax`;
USE `dac_dbt_2025`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `dac_dbt_2025`.`empmax` (`empcode`,`empname`,`deptcode`,`totalpay`) AS select `e`.`empcode` AS `empcode`,`e`.`empname` AS `empname`,`e`.`deptcode` AS `deptcode`,max(((`s`.`basic` + `s`.`allow`) - `s`.`deduct`)) AS `totalpay` from (`dac_dbt_2025`.`emp` `e` join `dac_dbt_2025`.`salary` `s` on((`e`.`empcode` = `s`.`empcode`))) group by `s`.`empcode`;

-- -----------------------------------------------------
-- View `dac_dbt_2025`.`femaleemployee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dac_dbt_2025`.`femaleemployee`;
USE `dac_dbt_2025`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `dac_dbt_2025`.`femaleemployee` AS select `e`.`empcode` AS `empcode`,`e`.`empname` AS `empname`,`e`.`sex` AS `sex`,`d`.`deptname` AS `deptname`,((`s`.`basic` + `s`.`allow`) - `s`.`deduct`) AS `totalSalary` from ((`dac_dbt_2025`.`emp` `e` join `dac_dbt_2025`.`dept` `d` on((`e`.`deptcode` = `d`.`deptcode`))) join `dac_dbt_2025`.`salary` `s` on(((`e`.`empcode` = `s`.`empcode`) and (`e`.`sex` = 'f') and `s`.`salmonth` >= all (select `s1`.`salmonth` from `dac_dbt_2025`.`salary` `s1`))));

-- -----------------------------------------------------
-- View `dac_dbt_2025`.`maleemployee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dac_dbt_2025`.`maleemployee`;
USE `dac_dbt_2025`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `dac_dbt_2025`.`maleemployee` AS select `e`.`empcode` AS `empcode`,`e`.`empname` AS `empname`,`e`.`sex` AS `sex`,`d`.`deptname` AS `deptname`,((`s`.`basic` + `s`.`allow`) - `s`.`deduct`) AS `totalSalary` from ((`dac_dbt_2025`.`emp` `e` join `dac_dbt_2025`.`dept` `d` on((`e`.`deptcode` = `d`.`deptcode`))) join `dac_dbt_2025`.`salary` `s` on(((`e`.`empcode` = `s`.`empcode`) and (`e`.`sex` = 'm') and `s`.`salmonth` >= all (select `s1`.`salmonth` from `dac_dbt_2025`.`salary` `s1`))));

-- -----------------------------------------------------
-- View `dac_dbt_2025`.`maxfemaleemployee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dac_dbt_2025`.`maxfemaleemployee`;
USE `dac_dbt_2025`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `dac_dbt_2025`.`maxfemaleemployee` AS select `e`.`empcode` AS `empcode`,`e`.`empname` AS `empname`,`e`.`sex` AS `sex`,`d`.`deptname` AS `deptname`,max(((`s`.`basic` + `s`.`allow`) - `s`.`deduct`)) AS `max(s.basic + s.allow - s.deduct)` from ((`dac_dbt_2025`.`emp` `e` join `dac_dbt_2025`.`dept` `d` on((`e`.`deptcode` = `d`.`deptcode`))) join `dac_dbt_2025`.`salary` `s` on((`e`.`empcode` = `s`.`empcode`))) where (((`s`.`basic` + `s`.`allow`) - `s`.`deduct`) >= all (select ((`s1`.`basic` + `s1`.`allow`) - `s1`.`deduct`) from (`dac_dbt_2025`.`salary` `s1` join `dac_dbt_2025`.`emp` `e1` on((`e1`.`empcode` = `s1`.`empcode`))) where (`e1`.`sex` = 'f')) and (`e`.`sex` = 'f')) group by `d`.`deptcode`;

-- -----------------------------------------------------
-- View `dac_dbt_2025`.`maxone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dac_dbt_2025`.`maxone`;
USE `dac_dbt_2025`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `dac_dbt_2025`.`maxone` AS select `e`.`empcode` AS `empcode`,`e`.`empname` AS `empname`,max(((`s`.`basic` + `s`.`allow`) - `s`.`deduct`)) AS `TotalPay` from (`dac_dbt_2025`.`emp` `e` join `dac_dbt_2025`.`salary` `s` on((`e`.`empcode` = `s`.`empcode`))) where ((`s`.`basic` + `s`.`allow`) - `s`.`deduct`) >= all (select ((`s2`.`basic` + `s2`.`allow`) - `s2`.`deduct`) from `dac_dbt_2025`.`salary` `s2`) group by `e`.`empcode`,`s`.`empcode`;

-- -----------------------------------------------------
-- View `dac_dbt_2025`.`maxsalaries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dac_dbt_2025`.`maxsalaries`;
USE `dac_dbt_2025`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `dac_dbt_2025`.`maxsalaries` AS select `e`.`empcode` AS `empcode`,`e`.`empname` AS `empname`,`e`.`deptcode` AS `deptcode`,max(((`s`.`basic` + `s`.`allow`) - `s`.`deduct`)) AS `totalPay` from (`dac_dbt_2025`.`emp` `e` join `dac_dbt_2025`.`salary` `s` on((`e`.`empcode` = `s`.`empcode`))) group by `s`.`empcode`;

-- -----------------------------------------------------
-- View `dac_dbt_2025`.`minfemalesalary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dac_dbt_2025`.`minfemalesalary`;
USE `dac_dbt_2025`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `dac_dbt_2025`.`minfemalesalary` AS select `dac_dbt_2025`.`e`.`empcode` AS `empcode`,`dac_dbt_2025`.`e`.`empname` AS `empname`,`dac_dbt_2025`.`e`.`sex` AS `sex`,`dac_dbt_2025`.`e`.`totalSalary` AS `totalSalary` from `dac_dbt_2025`.`femaleemployee` `e` where `dac_dbt_2025`.`e`.`totalSalary` <= all (select `dac_dbt_2025`.`femaleemployee`.`totalSalary` from `dac_dbt_2025`.`femaleemployee`);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
